### ISSUE TITLE
Lexxer does not tokenize on word boundaries correctely

### ISSUE THREAD

**Issue by erendrake** [KSP-KOS/TinyPG#1]
This is for fixing this issue from kOS in tinypg

https://github.com/KSP-KOS/KOS/pull/901

**Comment by Dunbaratu** [comment]
I am not 100% sure this 'bug' should be fixed.  Given that the regex for word boundries exists, I don't think we want to hardcode in TinyPG that it must be incapable of creating a token out of something that is multiple-word.

**Comment by Dunbaratu** [comment]
I was just saying I was used to using lexxers that take the longest choice they can.  That TinyPG doesn't do so is not necessarily, "wrong" - just not what I'm used to.  I really don't want to have to dig and dig and dig to "fix" what may just be a difference of design.

**Comment by erendrake** [comment]
alright, i misunderstood then. I was just trying to capture this in case we ever took a pass at tinyPG. If you are happy with this as the way it is ill close this ticket.
